
[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
workspace = "FQB354YeYLHky7omGhQXQxQ2QBcuYLq2QXiF4gdVogJt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://local-validator:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
